<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="challenge" nsURI="sa/edu/qu/coc/qupc/generator/challenge" nsPrefix="challenge">
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eAnnotations source="tests" references="#//Segment/average">
      <details key="tests1:String[]" value="['aabbccdd', 'aaabbaaac', 'abba', 'aabbaaabbbaaaabbbbaaaaaccccc', 'string', '1', 'abccbabbaavbbaac']"/>
      <details key="expected:double[]" value="[2.000000000, 2.250000000, 1.333333333, 3.500000000, 1.000000000, 1.000000000, 1.454545455]"/>
    </eAnnotations>
    <eOperations name="average" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="tests1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
